version: '2'

services:
  ovpn:
    image: giggio/openvpn-arm
    volumes:
      - ./data:/etc/openvpn
    ports:
      - '1194:1194/udp'
    cap_add:
      - NET_ADMIN
    environment:
      - DEBUG=${DEBUG:-0}
    restart: always
